name: build
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup GraalVM
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '20.2.0.java11'
    - name: Install native-image tool
      run: gu install native-image
    - name: Build
      run: ./build.sh
    - name: Run app
      run: ./target/app
